# Generated by Django 3.2.6 on 2021-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
