# Generated by Django 3.2.6 on 2021-09-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stocks',
            field=models.ManyToManyField(null=True, related_name='cusstock', to='stockmgmt.Stock'),
        ),
    ]
